title: Brain Tumor Segmentation in MRI — BRISC 2025
author: Luis D. Peñaranda Pérez · Johan D. López · David R. Márquez · Cristian C. Linero
logo: Imagenes/Logo.png

execute:
  execute_notebooks: 'off'

repository:
  url: https://github.com/luispenaranda08/brain-tumor-segmentation-brisc2025
  branch: main

html:
  use_issues_button: true
  use_repository_button: true